//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("HazyMail.NET")]
[assembly: System.Reflection.AssemblyDescription("Sending email with a simple command line tool")]
[assembly: System.Reflection.AssemblyProduct("HazyMail.NET")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Aurelien BOUDOUX 2014")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyVersion("1.0.34")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.34")]


